### ISSUE TITLE
Add balloon type FSI examples 

### ISSUE THREAD

**Issue by vincentchabannes** [feelpp/toolbox#12]
add FSI examples initially describe in
 [A solution for the incompressibility dilemma in partitioned fluid–structure interaction with pure Dirichlet fluid domains ( Ulrich KüttlerChristiane FörsterWolfgang A. Wall)](https://link.springer.com/article/10.1007/s00466-006-0066-5)
with the square and the bended domain.
Others description/results can be found in : 
- [Generalized Robin-Neumann explicit coupling schemes for incompressible fluid-structure interaction: stability analysis and numerics ( Miguel Angel Fernández, Jimmy Mullaert, Marina Vidrascu) ](https://hal.inria.fr/hal-00875819/PDF/RR-8384.pdf)

**Comment by prudhomm** [comment]
I added the benchmark to the first sprint with zenhub, have you all an account on zenhub ?

**Comment by lberti** [comment]
@vincentchabannes I have prepared the meshes for both the box and the structure, and I have started to write the configuration files. Do we have to implement the volume constraint that the article mentions? Is there already a routine implementing Lagrange multipliers? The article also recommends not to do the relaxation on the displacements but rather on the forces when passing between the two subproblems. Is it already the case or do we have to change something?

**Comment by prudhomm** [comment]
This is implemented. It corresponds to the incomprehensible case

**Comment by prudhomm** [comment]
@lberti  now you see just above the commit is there

**Comment by lberti** [comment]
If I put the "inlet" boundary condition, I just fix the velocity and not the pressure, as specified in 
http://docs.feelpp.org/toolboxes/0.104/cfd/toolbox/#_boundary_conditions ? 

The simulations with the box work only if I put define-pressure-cst=1 in the cfg file, but this apparently doesn't allow the pressure gradient to form, and as a result the balloon doesn't inflate. 

Moreover, in the structure case I have that the simulation doesn't even start and gives me this error 
``` Check failed: this->hasOrthonormalBasisVectors() basis vectors are not orthonormal  ```
that I obtained even with the bimaterial swimmer and I was not able to solve.

**Comment by lberti** [comment]
Should this issue be closed?

**Comment by prudhomm** [comment]
I thought there were still issues with the structure example

**Comment by prudhomm** [comment]
@vincentchabannes  what do you think ? close or keep open ?

**Comment by prudhomm** [comment]
I close the issue
