### ISSUE TITLE
Add spring CFD example 

### ISSUE THREAD

**Issue by prudhomm** [feelpp/toolbox#3]
the example is in angiotk repo

**Comment by prudhomm** [comment]
the documentation is now properly generated 
http://docs.feelpp.org/angiotk/0.1/centerlines/spring/

**Comment by prudhomm** [comment]
@francoisdh now the mesh generation explanation go in angiotk and the spring cfd #3 and csm #4 go in toolbox. They will need to be linked of course.
The mesh of the spring is uploaded to girder

**Comment by celineCQ** [comment]
I'm confused.
Shouldn't the comment about the angiotk doc be in the angiotk issue, linked here by the dependencies, that block this issue ? 
Cause I've been working on the toolbox & toolbox doc and now I'm not sure anymore of what remains to be done.

**Comment by prudhomm** [comment]
@celineCQ angiotk is only responsible for the mesh generation and is done (code+docs with antora) in `feelpp/angiotk`, the CFD and CSM parts are in `feelpp/toolbox` (note that there some docs in angiotk for them already).
If you are already done with the code+doc then awesome!
follow the steps here:
http://docs.feelpp.org/contribute/latest/#_documentation_setup

**Comment by prudhomm** [comment]
However in the angiotk documentation we link the mesh generation doc  to the CFD/CSM example and vice et versa so that the user can be from one another easily/quickly

**Comment by celineCQ** [comment]
I'm not done yet, obviously, only made the initial push of the branch with barely anything in it, I was just making sure the work wasn't going to be done twice.

**Comment by prudhomm** [comment]
I renamed https://github.com/feelpp/angiotk/issues/33 to be more explicit ;)

**Comment by celineCQ** [comment]
I seem to remind that we should put the angioTK generated mesh on Girder.
Should we add a python script that downloads the mesh in the toolbox?
If yes, how is privacy dealt with ? We want the script to work for all possible users since it's a toolbox, but we don't want the all possible users to access all Girder, am I right ?

**Comment by celineCQ** [comment]
Now waiting for the angio tk docs to be online (for reference) & for final mesh to be put on girder.
I also plan on changing the .png file for another vtkjs visualisation, would that be okay ?
