### ISSUE TITLE
Add Spring CSM example

### ISSUE THREAD

**Issue by prudhomm** [feelpp/toolbox#4]
this is in angiotk repo

/cc @vincentchabannes

**Comment by prudhomm** [comment]
the documentation is now properly generated:
http://docs.feelpp.org/angiotk/0.1/centerlines/spring/

**Comment by prudhomm** [comment]
@celineCQ @francoisdh where do we stand on this ?

**Comment by prudhomm** [comment]
I move this to the second sprint

**Comment by prudhomm** [comment]
@francoisdh @celineCQ do you have any issues with this ones? it needs to be finished by tuesday evening. Do you need help?

**Comment by prudhomm** [comment]
I haven't seen the update on this, this is part f the v106 @celineCQ @francoisdh could you finish the work ?
do you need help ?

**Comment by francoisdh** [comment]
@prudhomm I have pushed a [new branch](https://github.com/feelpp/toolbox/tree/case-spring-csm) with this case including its [documentation](http://docs.feelpp.org/cases/0.106-case-spring-csm/csm/README/#_a_href_spring_readme_class_page_spring_a). 
I will open a pull request.
