### ISSUE TITLE
Add cyclone CFD example

### ISSUE THREAD

**Issue by prudhomm** [feelpp/toolbox#5]
see course example

/cc @vincentchabannes

**Comment by prudhomm** [comment]
any update on this example ?

**Comment by prudhomm** [comment]
I remove @francoisdh  from this one so that he can work on a new testcase within the frame of his PhD

**Comment by prudhomm** [comment]
please add reference to issues in commit so that we can track down progress

**Comment by celineCQ** [comment]
Duly noted, gonna do my best to think about it on my next commit. Is there a "right" way to add reference to the issue ?

**Comment by romainhild** [comment]
https://help.github.com/articles/autolinked-references-and-urls/
https://help.github.com/articles/closing-issues-using-keywords/

**Comment by prudhomm** [comment]
@celineCQ do you think you can make it with this case by Tuesday evening? do you need help eg from @jbwahl or @vincentchabannes?

**Comment by celineCQ** [comment]
I've made progress on this case, will be over by today if I can save the time for it.

**Comment by celineCQ** [comment]
wainting to preview the doc online to start merge request

**Comment by celineCQ** [comment]
remaining issue with the vtkjs file, gotta check it tomorrow.

**Comment by prudhomm** [comment]
This is now set to be finished for v106 and the thrid sprint. @celineCQ

**Comment by prudhomm** [comment]
I haven't seen the update on this, this is part for the v106 @celineCQ @francoisdh could you finish the work ?
do you need help?

**Comment by francoisdh** [comment]
@prudhomm I will check and tell you, I thought this one worked fine.

**Comment by francoisdh** [comment]
I would like more information about this case, I believe there is some contradiction: 

- the current documentation and the [json](https://raw.githubusercontent.com/feelpp/toolbox/example-5-cyclone-cfd/examples/modules/cfd/examples/cyclone/cyclone.json) files mention water as the fluid being used, and provide matching density and viscosity. This suggests standard SI units are used.

- However, the [geo file](https://girder.math.unistra.fr/api/v1/file/5b1eaaffb0e9570499f66ba9/download) mentions a "(gas-solid) separator", and the mesh dimensions seem rather large: 6.45 x 1.75 x 1.35 ... are these meters ? 

Note: the mesh is even scaled down by 1e-2, see [cfg file](https://raw.githubusercontent.com/feelpp/toolbox/example-5-cyclone-cfd/examples/modules/cfd/examples/cyclone/cyclone.cfg)

What is the real device size ? And what kind of fluid flows inside ?

**Comment by francoisdh** [comment]
I don't need specific units, I agree SI should be used, it is what everyone would assume I guess. Thanks for the link, I actually already read this to get to know the physics but - of course - nothing is said about the **device dimensions**.

My problem is to understand the case, as I did not design it. So my questions are: 

- What is the fluid supposed to be ? Water at ambient ~20°C temperature ? _Then_ the json is fine. 
- But then, if the device mesh is indeed in meters, it seems rather large (more than **6m** long) isn't it ? ...

The case runs fine by the way.

**Comment by francoisdh** [comment]
@prudhomm Ok, my goal was to be about as thorough as with the spring CFD case. 

I will switch the model to NS because with meters long device and water (rho/mu ≈ 10^6), the Reynolds number is orders of magnitude to high for Stokes...
I will gladly update it later if needed - and revert to Stokes if we change the physics parameters.

**Comment by francoisdh** [comment]
@prudhomm @vincentchabannes 
I updated the documentation, it seems good enough to me compared to the spring CFD case. 

But I have trouble running the case with NS, it fails to converge. 
- I guess I should tweak the cfg? 
- What would be a good starting point?

**Comment by prudhomm** [comment]
@francoisdh this is not that easy and we shouldn't lose too much time here. you would need to understand what is the Reynolds number here. Solving for Stokes is enough for now, you mention that in the doc, and NS will come later down the road.

**Comment by prudhomm** [comment]
otherwise you need to understand a lot of things:
 - compute the Re to understand the regime
 - time stepping : you may have to reduce the time step for NS  
 - stabilisation methods
 - turbulence modelling

the last point we don't have it yet.

Have a look at _e.g._ http://iopscience.iop.org/article/10.1088/1757-899X/288/1/012142/pdf

or the other PDF attached. 

[23934_122215160513.pdf](https://github.com/feelpp/toolbox/files/2464736/23934_122215160513.pdf)
[IJCMESM_proof.pdf](https://github.com/feelpp/toolbox/files/2464737/IJCMESM_proof.pdf)

**Comment by francoisdh** [comment]
@prudhomm Ok, I switched back to Stokes, thanks for the PDFs :-) See PR #113
