### ISSUE TITLE
Chorus AIRBUS 2D testcase

### ISSUE THREAD

**Issue by prudhomm** [feelpp/toolbox#50]
## Description of the example

add the 2D Chorus AIRBUS testcase

The documentation is here

http://docs.feelpp.org/cases/0.105/heatfluid/cabin/README/

**Comment by jbwahl** [comment]
I'm on it.
@prudhomm  I guess there was a keyboard issue with the title?

**Comment by prudhomm** [comment]
that's my son who just played with my laptop. Quite dangerous it seems

**Comment by prudhomm** [comment]
@jbwahl is it finished?

**Comment by prudhomm** [comment]
@jbwahl I looked at the documentation of the testcase, there are no results, no comments and very little description. Could you extract your PhD work and incorporate it here ? Of course you should cite your thesis work at the end.

**Comment by jbwahl** [comment]
It is not exactly the same configuration that what I used in my Ph.D
This one is a transient problem. I can add a video of the temperature field but I have not so many results.
