### ISSUE TITLE
Add pendulum CSM example

### ISSUE THREAD

**Issue by prudhomm** [feelpp/toolbox#6]
the testcase is described in the Feel++ courses

@olmes-sch  you will work with @celineCQ 

/cc @vincentchabannes

**Comment by celineCQ** [comment]
@olmes-sch could we start working on it ?

**Comment by prudhomm** [comment]
@celineCQ, @olmes-sch  has left. 

any progress on your side?

**Comment by prudhomm** [comment]
@celineCQ do you need help with the testcase? @francoisdh @romainhild or @vincentchabannes can perhaps help you with it? I would like it to be merged by Tuesday evening so that we can discuss it on Wednesday

**Comment by celineCQ** [comment]
Haven't have the time to start it yet, if all go smooth it'll be over by tomorrow, if I don't find the time, I'll ask around.

**Comment by celineCQ** [comment]
Still having few issues with this one, trying to make sense of it at the moment.

**Comment by celineCQ** [comment]
Convergence issues arose in 3D, working on it.
Gonna split the 2D and 3D case, the 2D case is nearly ready.

**Comment by prudhomm** [comment]
I haven't seen the update on this, this is part of the v106 @celineCQ @francoisdh could you finish the work ?

**Comment by francoisdh** [comment]
@prudhomm Ok, I will investigate it
