### ISSUE TITLE
add 3D building thermal simulation 

### ISSUE THREAD

**Issue by prudhomm** [feelpp/toolbox#8]
add thermal building example

/cc @vincentchabannes

**Comment by celineCQ** [comment]
@miinguyen @Weimin453 could you detail the issue you found this morning ?

**Comment by miinguyen** [comment]
![screen shot 2018-05-16 at 17 49 58](https://user-images.githubusercontent.com/25435287/40128351-ac98d4f8-5931-11e8-8918-88bd22bc291f.png)

**Comment by prudhomm** [comment]
@Weimin453 where do you stand on this testcase ? 
looking at http://docs.feelpp.org/examples/wip-example-8/heat/3Dbuilding/README/ it is unfinished, there are no results and no analysis

**Comment by celineCQ** [comment]
There remains a bug with vtkjs, we're looking into it w/ @vincentchabannes

**Comment by vincentchabannes** [comment]
it has been fixed

**Comment by prudhomm** [comment]
should the issue be closed?

**Comment by prudhomm** [comment]
could we attempt at some point the aerothermal flow on cesga ?
