### ISSUE TITLE
Compute Min, Max and Mean outputs 

### ISSUE THREAD

**Issue by prudhomm** [feelpp/toolbox#85]
**Is your feature request related to a problem ? Please describe.**
is it possible to compute outputs such as
 * min
 * max
 * mean
either global or local(markers)

**Describe the solution you'd like**

if yes, how is it done in the PostProcessing section?

**Additional context**
This was asked by one participant of ECMI 2018 conference.

**Comment by prudhomm** [comment]
@vincentchabannes we should add the documentation for that. Could you post an example here for example and I add it to the documentation ?

**Comment by prudhomm** [comment]
@vincentchabannes is it finished? if it is then I move this back to release 105

**Comment by vincentchabannes** [comment]
why 105? we are in 106. I will try to do the pull request today. The code is finished and I have written also the [doc](http://docs.feelpp.org/toolboxes/0.105/what-is-a-toolbox/#_statistics). Feedbacks will be great

**Comment by prudhomm** [comment]
yeah right sorry 106 of course
